development:
  aws_access_key_id: 'AKIAJJWCERXLBPMNAGGA'
  aws_secret_access_key: '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'
  provider: 'AWS'

test:
  aws_access_key_id: 'AKIAJJWCERXLBPMNAGGA'
  aws_secret_access_key: 'SdfwkoDDs7vZRdUg9zXNvrHUF4GY8nqXCrfGN4hp'
  provider: 'AWS'

# set these environment variables on your prod server
production:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  provider: 'AWS'
